"""add is_admin to organizations

Revision ID: 3a75e60c89a1
Revises: 58fd8c9eff3a
Create Date: 2026-03-14 19:44:19.316003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a75e60c89a1'
down_revision: Union[str, Sequence[str], None] = '58fd8c9eff3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('is_admin', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'is_admin')
    # ### end Alembic commands ###
