"""add debug_mode to api_keys and debug_logs table

Revision ID: 58fd8c9eff3a
Revises: 6dfa0ac14cca
Create Date: 2026-03-14 17:26:10.874405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58fd8c9eff3a'
down_revision: Union[str, Sequence[str], None] = '6dfa0ac14cca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('debug_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usage_record_id', sa.UUID(), nullable=False),
    sa.Column('api_key_id', sa.UUID(), nullable=False),
    sa.Column('request_body', sa.Text(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usage_record_id'], ['usage_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_debug_logs_api_key_id_created_at', 'debug_logs', ['api_key_id', 'created_at'], unique=False)
    op.create_index('ix_debug_logs_created_at', 'debug_logs', ['created_at'], unique=False)
    op.add_column('api_keys', sa.Column('debug_mode', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_keys', 'debug_mode')
    op.drop_index('ix_debug_logs_created_at', table_name='debug_logs')
    op.drop_index('ix_debug_logs_api_key_id_created_at', table_name='debug_logs')
    op.drop_table('debug_logs')
    # ### end Alembic commands ###
