"""Add usage_records and daily_usage_summaries tables

Revision ID: 6dfa0ac14cca
Revises: a3b7c9d1e2f4
Create Date: 2026-03-14 16:22:48.064793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dfa0ac14cca'
down_revision: Union[str, Sequence[str], None] = 'a3b7c9d1e2f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_usage_summaries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('api_key_id', sa.UUID(), nullable=False),
    sa.Column('netuid', sa.Integer(), nullable=False),
    sa.Column('subnet_name', sa.String(length=64), nullable=False),
    sa.Column('summary_date', sa.Date(), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('p50_latency_ms', sa.Integer(), nullable=False),
    sa.Column('p95_latency_ms', sa.Integer(), nullable=False),
    sa.Column('p99_latency_ms', sa.Integer(), nullable=False),
    sa.Column('total_prompt_tokens', sa.BigInteger(), nullable=False),
    sa.Column('total_completion_tokens', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key_id', 'netuid', 'summary_date', name='uq_daily_usage_summaries_key_subnet_date')
    )
    op.create_index('ix_daily_usage_summaries_org_id_netuid_date', 'daily_usage_summaries', ['org_id', 'netuid', 'summary_date'], unique=False)
    op.create_table('usage_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('api_key_id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('subnet_name', sa.String(length=64), nullable=False),
    sa.Column('netuid', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.Column('miner_uid', sa.String(length=64), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_usage_records_api_key_id_created_at', 'usage_records', ['api_key_id', 'created_at'], unique=False)
    op.create_index('ix_usage_records_created_at', 'usage_records', ['created_at'], unique=False)
    op.create_index('ix_usage_records_org_id_netuid_created_at', 'usage_records', ['org_id', 'netuid', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_usage_records_org_id_netuid_created_at', table_name='usage_records')
    op.drop_index('ix_usage_records_created_at', table_name='usage_records')
    op.drop_index('ix_usage_records_api_key_id_created_at', table_name='usage_records')
    op.drop_table('usage_records')
    op.drop_index('ix_daily_usage_summaries_org_id_netuid_date', table_name='daily_usage_summaries')
    op.drop_table('daily_usage_summaries')
    # ### end Alembic commands ###
