"""drop_observation_count_from_miner_scores

Revision ID: c15784f7f7bb
Revises: d918598f5b47
Create Date: 2026-03-14 11:16:13.118523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c15784f7f7bb'
down_revision: Union[str, Sequence[str], None] = 'd918598f5b47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('miner_scores', 'observation_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('miner_scores', sa.Column('observation_count', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
