"""add_miner_scores_table

Revision ID: d918598f5b47
Revises: 37ec55ff6595
Create Date: 2026-03-14 10:44:53.655487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd918598f5b47'
down_revision: Union[str, Sequence[str], None] = '37ec55ff6595'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('miner_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('miner_uid', sa.Integer(), nullable=False),
    sa.Column('hotkey', sa.String(length=64), nullable=False),
    sa.Column('netuid', sa.Integer(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('total_requests', sa.Integer(), nullable=False),
    sa.Column('successful_requests', sa.Integer(), nullable=False),
    sa.Column('avg_latency_ms', sa.Float(), nullable=False),
    sa.Column('observation_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hotkey', 'netuid', name='uq_miner_scores_hotkey_netuid')
    )
    op.create_index('ix_miner_scores_netuid_quality_score', 'miner_scores', ['netuid', 'quality_score'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_miner_scores_netuid_quality_score', table_name='miner_scores')
    op.drop_table('miner_scores')
    # ### end Alembic commands ###
